# Generated by Django 5.0.4 on 2024-04-12 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('subject', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('view_count', models.IntegerField()),
                ('post_create_time', models.DateTimeField()),
                ('id', models.AutoField(default=1, primary_key=True, serialize=False)),
            ],
        ),
    ]
