# Generated by Django 5.0.4 on 2024-04-14 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('tag', models.CharField(max_length=50)),
                ('view_count', models.IntegerField()),
                ('post_create_time', models.DateTimeField()),
                ('user_id', models.CharField(max_length=50)),
                ('is_del', models.BooleanField(default=False)),
            ],
        ),
    ]
