# Generated by Django 5.0.4 on 2024-04-15 01:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0001_initial'),
        ('page1', '0002_alter_answer_id_alter_post_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('tag', models.CharField(max_length=50)),
                ('view_count', models.IntegerField()),
                ('post_create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_del', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mypost', to='page1.post')),
            ],
            options={
                'db_table': 'mypost',
            },
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
