# Generated by Django 5.0.4 on 2024-04-15 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0002_mypost_delete_post'),
        ('page1', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mypost',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mypost', to='page1.profile'),
        ),
    ]
