# Generated by Django 5.0.4 on 2024-04-16 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0003_alter_mypost_user_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyPost',
        ),
    ]
