# Generated by Django 5.0.4 on 2024-04-14 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_alter_posting_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posting',
            name='post_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
