# Generated by Django 5.0.4 on 2024-04-15 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_alter_posting_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posting',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='community/uploads/'),
        ),
        migrations.AlterField(
            model_name='posting',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='community/uploads/'),
        ),
        migrations.AlterField(
            model_name='posting',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='community/uploads/'),
        ),
    ]
