# Generated by Django 5.0.4 on 2024-04-15 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_alter_posting_image1_alter_posting_image2_and_more'),
        ('page1', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posting',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posting', to='page1.profile'),
        ),
    ]
