# Generated by Django 5.0.4 on 2024-04-16 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_category_posting_is_del_alter_posting_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posting',
            name='author',
            field=models.CharField(max_length=50),
        ),
    ]
