# Generated by Django 5.0.4 on 2024-04-16 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0011_remove_posting_likes_posting_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posting',
            name='likes',
        ),
        migrations.AddField(
            model_name='posting',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
